repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      line_length: 79
-   repo: https://github.com/thlorenz/doctoc
    rev: master
    hooks:
    -   id: doctoc
